# Generated by Django 4.2.7 on 2023-12-16 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
