# Generated by Django 4.2.7 on 2023-12-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_tag_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
